###############################################################################
# Dock Applications
###############################################################################

apps = [
  "/Applications/Google Chrome.app",
  "/Applications/Safari.app",
  "/Applications/Arc.app",
  "/Applications/Ghostty.app",
  "/Applications/Cursor.app",
  "/Applications/Visual Studio Code.app",
  "/Applications/CotEditor.app",
  "/Applications/ChatGPT.app",
  "/Applications/Claude.app",
  "/Applications/DBeaver.app",
  "/Applications/Notion.app",
  "/Applications/Notion Calendar.app",
  "/Applications/Obsidian.app",
  "/Applications/1Password.app",
  "/Applications/Granola.app",
  "/Applications/Trello.app",
  "/Applications/Raycast.app"
]
