###############################################################################
# Dock Applications
###############################################################################

apps = [
  "/Applications/Ghostty.app",
  "/Applications/Cursor.app",
  "/Applications/Visual Studio Code.app",
  "/Applications/Safari.app",
  "/Applications/Google Chrome.app",
  "/Applications/Arc.app",
  "/Applications/ChatGPT.app",
  "/Applications/Claude.app",
  "/Applications/DBeaver.app",
  "/Applications/Microsoft Teams.app",
  "/Applications/Microsoft Outlook.app",
  "/Applications/Microsoft PowerPoint.app",
  "/Applications/Microsoft OneNote.app",
  "/Applications/Notion.app",
  "/Applications/Notion Calendar.app",
  "/Applications/1Password.app",
  "/Applications/Obsidian.app",
  "/Applications/Trello.app",
  "/Applications/Raycast.app",
  "/Applications/Self Service.app"
]